Bunch of changes, optimizations and changes to how ssh works.

diff --git a/rsyncsnap b/rsyncsnap
--- a/rsyncsnap
+++ b/rsyncsnap
@@ -23,29 +23,17 @@
 # ║ VARIABLES                                                                  ║
 # ╚════════════════════════════════════════════════════════════════════════════╝
 version="1.0.0-alpha"
-filename="${0##*/}"                     # Remove /full/path/ to to get only filename
-basename="${filename%.*}"               # Remove .ext from filename to get basename
-program_title="${basename}"             # Get program title from basename of file
-rsync_options=(-arvhxSR --numeric-ids)  # Rsync command options
-#rsync_options=(-avhxRHAWXS)
+program_title="rsyncsnap"
+rsync_options=(-arvhxSR --numeric-ids)                           # Rsync command options (-avhxRHAWXS)
 ssh_options=(-oStrictHostKeyChecking=no -oLogLevel=QUIET -n -q)  # SSH command options (Remove -q to have SSH verbose output.)
 datetime="$(printf '%(%Y-%m-%d_%H.%M.%S)T' -1)"                  # datetime formatting
 logtmp="$(mktemp)" || logtmp="/tmp/rsyncsnap-${RANDOM}.tmp"      # Temp log location
-source="${1%/}"                         # Source location removing trailing slash variable
-destination="${2%/}"                    # Destination directory to store backups removing trailing slash from variable)
-## Set variables if (ssh) colon detected in destination
-if [[ "${destination}" = *:* ]]; then
-  use_ssh="Y"
-  ssh_server="${destination%:*}"
-  destination_dir="${destination#*:}"
-else
-  destination_dir="${destination}"
-fi
-## Name the destination backup archive based on directory base or include filename
-backup_base="${source[0]##*/}"
-backup_base="${backup_base%.*}"
-# Softlink name (add/remove . to beginning if want link hidden or visable in backup)
-current_link="${backup_base}-current"
+source="${1%/}"                                                  # Source location removing trailing slash variable
+destination="${2%/}"                                             # Destination directory to store backups removing trailing slash from variable)
+if [[ "${destination}" = *:* ]]; then use_ssh="Y"; ssh_server="${destination%:*}"; destination_dir="${destination#*:}"; else destination_dir="${destination}"; fi # Set variables if (ssh) colon detected in destination
+backup_base="${source[0]##*/}"    # Remove full path
+backup_base="${backup_base%.*}"   # Remove extention
+current_link="${backup_base}-current" # Softlink name (add/remove . to beginning if want link hidden or visable in backup)
 
 # ╔════════════════════════════════════════════════════════════════════════════╗
 # ║ FUNCTIONS                                                                  ║
@@ -69,23 +57,27 @@ USAGE:
 --------------------------------------------------------------------------------
 OPTIONS:
 
--s --snapshots      Amount of snapshots to keep: --snapshots 30  (Keep 30 total snapshots)
+-s --snapshots      Amount of snapshots to keep:
+                    --snapshots 30  (Keep 30 total snapshots)
 
--d --days           How many days to keep snapshots: --days 45  (Keep 45 days of snapshots)
-                    *Option not recommended when using SSH for destination
+-d --days           How many days to keep snapshots:
+                    --days 45  (Keep 45 days of snapshots)
+                    *Does not work when using remote/ssh as destination
 
 -e --exclude        Path of exclude file: --exclude /home/user/rsyncsnap.exclude
 -------------------------------------
--l --logfile        Directory and filename location to create/append log file: --logfile /home/user/rsyncsnap.log
+-l --logfile        Directory and filename location to create/append log file:
+                    --logfile /home/user/rsyncsnap.log
 
--m --mail --email   Send email using mail command: --mail user@domain.com  //  --mail root
+-m --mail --email   Send email using mail command:
+                    --mail user@domain.com // --mail root
                   
 --syslog            Send status to syslog using logger
 -------------------------------------
 --rsync-options     Default: ${rsync_options[*]}
                     Use custom rsync options instead of built-in default.
                     **Must Use \"quotes\"
-                    --rsync-options \"-axHAWXS --numeric-ids\"
+                    --rsync-options \"-avhxRHAWXS --numeric-ids\"
 -------------------------------------
 --pull              Perform pull backup from remote server to local destination
                     Directories must have : <colon> before their names
@@ -97,7 +89,7 @@ OPTIONS:
                     **Must Use \"quotes\"
                     --rsync-path=\"sudo user\"
 -------------------------------------
--v | --verbose      Display more verbose output
+-v | --verbose      Display more verbose output like snapshot amount information
 --dryrun            Perform rsync using --dry-run to test backup.
 --debug             Use set-x bash option when running script.
 -V | --version      Version information
@@ -116,6 +108,11 @@ EXAMPLES:
   rsyncsnap /home/user /mnt/backups
   rsyncsnap /root/rsyncsnap.include user@server:/home/user/backups
 
+PULL BACKUP FROM REMOTE SERVER USING SSH:
+
+  rsyncsnap <remote_user@server_to_backup> <local_destination_to_store_backups>
+            --pull \"<:directories :on :remote: :server>\"
+  
   rsyncsnap user@server /srv/backups/
             --pull \":/etc/ :/home/ :/usr/local/\" \\
             --pull-sudo user \\
@@ -123,13 +120,12 @@ EXAMPLES:
 - Using single directory as source will backup single directory.
 - Using include file as source will backup directories listed in file.
 - Can use multiple source directories within \"quotes\"
-  \"/home/user/ /etc/ /usr/local/bin/\"
+  \"/home/user /etc /usr/local/bin\"
 --------------------------------------------------------------------------------
-SSH:
-- Use --ssh-options to add regular SSH arguments to command
-  --ssh-options \"-p 22 -i /home/user/.ssh/key\"
-- Recommended using ssh key authentication for jobs using: ~/.ssh/config file
-
+NAME OF BACKUP:
+- Backup is named based on include filename or the source directory name
+  if doing single directory backup.
+--------------------------------------------------------------------------------
 RESTORE:
 - To restore files from backup, manually copy files from backup date/time
   in destination directory to original or alternate location.
@@ -176,97 +172,59 @@ perform_rsync() {
   fi
 }
 
-create_softlink() {
-  msg "Creating new softlink to latest version backup at ${destination}"
-  if [[ "${use_ssh}" == "Y" ]]; then
-    # SSH - Create soft link of current date-time to backup just created -- DO NOT QUOTE VARIABLES IN SSH
-    if ! ssh "${ssh_options[@]}" "${ssh_server}" "rm -f ${destination_dir}/${current_link} ; ln -s ${destination_dir}/${backup_base}@${datetime} ${destination_dir}/${current_link}"; then
-      err "creating SSH softlink on ${ssh_server} to ${destination_dir}/${current_link}"
+local_softlink_snapshots() {
+  # -- Create soft link of current date-time to backup just created
+  if ! rm -f "${destination_dir}"/"${current_link}"; then fail "Issues removing old softlink"; fi
+  if ! ln -s "${destination_dir}"/"${backup_base}"@"${datetime}" "${destination}"/"${current_link}"; then fail "Creating softlink to ${destination}/${current_link}"; else msg "Created/updated softlink to latest version backup at ${destination}"; fi
+  # --- Keep snapshots by (amount)
+  if [[ -n "${snapshot_amount}" ]]; then
+    # Get amount of backups in destination directory
+    num_existing="$(find "${destination_dir}"/"${backup_base}"@* -maxdepth 0 -type d | wc -l)"
+    # Remove snapshots amount if over snapshot limit
+    if [[ "${num_existing}" -gt "${snapshot_amount}" ]]; then
+      ((over="${num_existing}"-"${snapshot_amount}"))
+      if ! find "${destination_dir}"/"${backup_base}"@* -maxdepth 0 -type d | head -n "${over}" | while read -r s; do rm -rf "${s}"; done
+        then warn "Removing older snapshots -amount- from ${destination}"; else msg "Removed old snapshots by amount - Limit: ${snapshot_amount}"; fi
     fi
-  else
-    # Local - Create soft link of current date-time to backup just created
-    rm -f "${destination_dir}"/"${current_link}"
-    if ! ln -s "${destination_dir}"/"${backup_base}"@"${datetime}" "${destination}"/"${current_link}"; then err "creating LOCAL softlink to ${destination}/${current_link}"; fi
   fi
-}
-
-remove_old_snapshots() {
-  if [[ -d "${destination_dir}"/"${current_link}" ]]; then
-    # --- Keep snapshots by amount
-    if [[ -n "${snapshot_amount}" ]]; then
-      # Get number of backups in destination directory
-      num_existing="$(find "${destination_dir}"/"${backup_base}"@* -maxdepth 0 -type d | wc -l)"
-      # Remove snapshots amount if over snapshot limit
-      if [[ "${num_existing}" -gt "${snapshot_amount}" ]]; then
-        msg "Removing old snapshots by amount (Limit: ${snapshot_amount})"
-        ((over="${num_existing}"-"${snapshot_amount}"))
-        if ! find "${destination_dir}"/"${backup_base}"@* -maxdepth 0 -type d | head -n "${over}" | while read -r s; do rm -rf "${s}"; done
-        then
-          warn "Removing older snapshots (amount) from ${destination}"
-        fi
-      fi
-    fi
-    # --- Keep snapshots by days
-    if [[ -n "${snapshot_amount_days}" ]]; then
-      # List snapshot keep days if hit limit
-      if [[ "$(find "${destination_dir}"/"${backup_base}"@* -mtime +"${snapshot_amount_days}" -print)" ]]; then
-        msg "Removing old snapshots by days   (Limit: ${snapshot_amount_days})"
-      fi
-      if ! find "${destination_dir}"/"${backup_base}"@* -maxdepth 0 -type d -mtime +"${snapshot_amount_days}" -exec rm -rf {} \;
-      then
-        warn "Removing older snapshots (days) from ${destination}"
-      fi
-    fi
-  else
-    warn "Destination directory not found at ${destination} -- Unable to remove old snapshots!"
+  # --- Keep snapshots by (days)
+  if [[ -n "${snapshot_amount_days}" ]]; then
+    # List snapshot keep days if hit limit
+    if ! find "${destination_dir}"/"${backup_base}"@* -maxdepth 0 -type d -mtime +"${snapshot_amount_days}" -exec rm -rf {} \;
+      then warn "Removing older snapshots -days- from ${destination}"; else msg "Removed old snapshots by days - Limit: ${snapshot_amount_days}"; fi
   fi
-
   # List Snapshots
   if [[ "${verbose}" == "Y" ]]; then msg "Listing backup snapshots at ${destination}"; fi
-  if [[ "${verbose}" == "Y" ]]; then printf '%s \n' "$(ls -d1 ${destination_dir}/${backup_base}@*)" 2>&1 | tee -a "${logtmp}"; fi
+  if [[ "${verbose}" == "Y" ]]; then printf '%s \n' "$(ls -d1 "${destination_dir}"/"${backup_base}"@*)" 2>&1 | tee -a "${logtmp}"; fi
 }
 
-ssh_remove_old_snapshots() {
-  # Keep snapshots by amount -- DO NOT QUOTE VARIABLES IN SSH
-  if [[ -n "${snapshot_amount}" ]]; then
-    msg "Checking if snapshots need to be pruned to set limit"
-    if ! ssh "${ssh_options[@]}" "${ssh_server}" "
-    if [[ -n ${snapshot_amount} ]]; then
-      # Create variable count of backups in directory at destination
-      num_existing=\$(find ${destination_dir}/${backup_base}@* -maxdepth 0 -type d |wc -l)
-      # Remove snapshots amount if over snapshot limit
-      if [[ \${num_existing} -gt ${snapshot_amount} ]]; then
-        echo "[${program_title}] Removing old snapshots by amount - Limit: ${snapshot_amount}"
-        let over=${num_existing}-${snapshot_amount}
-        if ! find ${destination_dir}/${backup_base}@* -maxdepth 0 -type d | head -n \${over} | while read s; do rm -rf \${s}; done
-        then
-          echo "Removing older snapshots amount from ${destination}"
-        fi
-        # List Snapshots
-        #if [[ ${verbose} == "Y" ]]; then echo "[${program_title}] Listing backup snapshots at ${destination}"; fi
-        #if [[ ${verbose} == "Y" ]]; then ls -d1 ${destination_dir}/${backup_base}@*; fi
-      fi
-    fi
-    "
-    then
-      warn "SSH removing older amount snapshots from ${destination}"
+ssh_softlink_snapshots() {
+ssh "${ssh_options[@]}" "${ssh_server}" "
+  # -- Create/Update Softlink
+  if ! rm -f ${destination_dir}/${current_link}; then printf '%s \n' '[ SSH- ] Issues removing old softlink'; fi
+  if ! ln -s ${destination_dir}/${backup_base}@${datetime} ${destination_dir}/${current_link}; then printf '%s \n' '[ SSH- ] Failed creating softlink to ${destination}/${current_link}'; else printf '%s \n' '[ SSH- ] Created/updated softlink to latest version backup at ${destination}'; fi
+  # -- Remove old snapshots (AMOUNT)
+  if [[ ${snapshot_amount} ]]; then
+    # Get amount of backups in destination directory
+    num_existing=\$(find ${destination_dir}/${backup_base}@* -maxdepth 0 -type d | wc -l)
+    # Remove snapshots if over snapshot limit
+    if [[ \${num_existing} -gt ${snapshot_amount} ]]; then
+      ((over=${num_existing}-${snapshot_amount}))
+      if ! find ${destination_dir}/${backup_base}@* -maxdepth 0 -type d | head -n \${over} | while read -r s; do rm -rf \${s}; done
+        then printf '%s \n' '[ SSH- ] Issues removing older snapshots -amount- from ${destination}'; else printf '%s \n' '[ SSH- ] Removed old snapshots by amount - Limit: ${snapshot_amount}'; fi
     fi
   fi
-  # Keep snapshots by days
-  if [[ -n "${snapshot_amount_days}" ]]; then
-    msg "SSH Removing old snapshots from ${destination_dir} if days reached (Limit: ${snapshot_amount_days})"
-    if ! ssh "${ssh_options[@]}" "${ssh_server}" "find ${destination_dir}/${backup_base}@* -maxdepth 0 -type d -mtime +${snapshot_amount_days} -exec rm -rf {} \;"
-    then
-      warn "SSH removing older days snapshots from ${destination}/${current_link}"
-    fi
-  fi
+  # -- List Snapshots
+  if [[ ${verbose} == Y ]]; then printf '%s \n' '[ SSH- ] Listing backup snapshots at ${destination}'; fi
+  if [[ ${verbose} == Y ]]; then printf '%s \n' \$(find ${destination_dir}/${backup_base}@* -maxdepth 0 -type d) 2>&1 | tee -a ${logtmp}; fi
+"
 }
 
 rsync_dryrun() {
-  printf '%s\n\n' "[${program_title}] Performing dry-run of rsync for testing - Actual backup will NOT be performed"
+  printf '%s\n\n' "[ DRYRUN ] Performing dry-run of rsync for testing - Actual backup will NOT be performed"
   rsync_options+=( --dry-run)
   perform_rsync
-  printf '%s\n\n' "[${program_title}] Finished performing dry-run of rsync for testing - Actual backup was NOT performed"
+  printf '%s\n\n' "[ DRYRUN ] Finished performing dry-run of rsync for testing - Actual backup was NOT performed"
   exit 0
 }
 
@@ -286,7 +244,7 @@ command_options() {
     -d|--days) snapshot_amount_days="$2" ; if [[ ! "${2}" ]] || [[ "${2}" == -* ]]; then printf '%s \n' "Option argument not entered"; exit 1; fi; shift ;;
     --rsync-options) rsync_options=( "$2") ; if [[ ! "${2}" ]] || [[ "${2}" == -* ]]; then printf '%s \n' "Option argument not entered"; exit 1; fi; shift ;;
     --pull-sudo) sudo_user="$2" ; if [[ ! "${2}" ]] || [[ "${2}" == -* ]]; then printf '%s \n' "Option argument not entered"; exit 1; fi; sudo_command=(--rsync-path="sudo ${sudo_user}"); shift ;;
-    --pull) pull_sources=($2) ; if [[ ! "${2}" ]] || [[ "${2}" == -* ]]; then printf '%s \n' "Option argument not entered"; exit 1; fi; backup_type="PULL"; use_ssh="N"; shift ;;
+    --pull) pull_sources=( "$2") ; if [[ ! "${2}" ]] || [[ "${2}" == -* ]]; then printf '%s \n' "Option argument not entered"; exit 1; fi; backup_type="PULL"; use_ssh="N"; shift ;;
     -l|--logfile) logfile="$2"; if [[ ! "${2}" ]] || [[ "${2}" == -* ]]; then printf '%s \n' "Option argument not entered"; exit 1; fi; shift ;;
     -m|--mail|--email) mail_address="$2"; if [[ ! "${2}" ]] || [[ "${2}" == -* ]]; then printf '%s \n' "Option argument not entered"; exit 1; fi; shift ;;
     --syslog) sendsyslog="Y" ;;
@@ -311,13 +269,12 @@ main() {
   if [[ "${backup_type}" == "PULL" ]]; then msg "[PULLING] ${source[*]} to ${destination}"; else msg "[PUSHING] ${source[*]} to ${destination}"; fi
   msg "------------------------------------------------------------------------"
   perform_rsync
-  create_softlink
-  if [[ "${use_ssh}" == "Y" ]] || [[ "${destination_dir}" = *:* ]]; then ssh_remove_old_snapshots; else remove_old_snapshots; fi  # Perform other tasks (local or ssh)
+  if [[ "${use_ssh}" == "Y" ]] || [[ "${destination_dir}" = *:* ]]; then ssh_softlink_snapshots; else local_softlink_snapshots; fi
   finish=$(date +%s)
   msg "------------------------------------------------------------------------"
   msg "[ Total Time :] $(( (${finish}-${start}) / 60 )) minutes, $(( (${finish}-${start}) % 60 )) seconds"
   msg "(END) rsyncsnap hardlink version backup"
-  if [[ "${sendsyslog}" == "Y" ]]; then if ! logger -s -t rsyncsnap "${log_subject[0]}" "${log_subject[2]}" > /dev/null 2>&1; then warn="Issue sending message to syslog via logger"; fi; fi
+  if [[ "${sendsyslog}" == "Y" ]]; then if ! logger -s -t rsyncsnap "${log_subject[0]}" "${log_subject[2]}" > /dev/null 2>&1; then warn "Issue sending message to syslog via logger"; fi; fi
   if [[ "${mail_address}" ]]; then if ! mail -s "${log_subject[*]}" "${mail_address}" < "${logtmp}"; then warn "Issue sending mail to: ${mail_address}"; fi; fi
   cleanup
 }
